name: PR workflow
on: 
  pull_request:
    types: [closed]
jobs:
  pr-dev-code-conformity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Specify node version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: npm install
      - name: ESLint code check
        run: npm run lint
      - name: Prettier code check
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --check ./src/**/*.js
  pr-dev-build-and-deploy: 
    runs-on: ubuntu-latest
    needs: [pr-dev-code-conformity]
    if: ${{ (needs.pr-dev-code-conformity.result=='success') }}
    environment: 
          name: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Specify node version
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install modules
        run: npm install
      - name: Automated Tests
        run: npm run test
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}